#!/bin/bash
set -x

HERE=$(cd "${0%/*}" && echo $PWD)

echo "XDG_CONFIG_HOME: $XDG_CONFIG_HOME"
if [ "$XDG_CONFIG_HOME" != "" ]; then # If use --appimage-portable-config
    config_path="$XDG_CONFIG_HOME/sacd_extract_AppImage"
else # Default mode, use ~/.config/
    config_path="$HOME/.config/sacd_extract_AppImage"
fi
config_path=$(echo "$config_path/" | sed 's/\/\//\//g') # // to /

echo "config_path $config_path"
mkdir "$config_path"

cp "$HERE/sacd_extract/sacd_extract" "$config_path/"

if [ ! -f "$config_path/SACDExtractGUI.properties" ]; then # Check if configuration file exists
    echo "Configuration not found! - Coping default one"
    cp "$HERE/sacd_extract/SACDExtractGUI.properties" "$config_path/"
fi
echo "sacd_extract configuration file: $config_path/SACDExtractGUI.properties"
cd "$config_path/"

config_path_sed=$(echo "$config_path" | sed 's/\//\\\//g')
sed -i "s/FOLDER\//$config_path_sed/1" SACDExtractGUI.properties
cat SACDExtractGUI.properties

$HERE/runtime/bin/java -jar $HERE/sacd_extract/SACDExtractGUI.jar
