#
#Mon Apr 27 10:34:56 BRT 2026
output1=
processingType=0
output2=
ipAddrPort=2002
ipAddr0=192
ipAddr1=168
ipAddr2=1
program=FOLDER/sacd_extract
ipAddr3=100
output2Selected=false
multi=false
nopad=false
cue=false
print=false
decompress=true
output1Selected=false
stereo=true
inputType=0
